// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"
)

type FornecedoresDado struct {
	ID                            int32
	PartnerID                     string
	PartnerName                   string
	CustomerID                    string
	CustomerName                  string
	CustomerDomainName            string
	CustomerCountry               string
	MpnID                         int32
	Tier2MpnID                    int32
	InvoiceNumber                 string
	ProductID                     string
	SkuID                         string
	AvailabilityID                string
	SkuName                       string
	ProductName                   string
	PublisherName                 string
	PublisherID                   string
	SubscriptionDescription       string
	SubscriptionID                string
	ChargeStartDate               time.Time
	ChargeEndDate                 time.Time
	UsageDate                     time.Time
	MeterType                     string
	MeterCategory                 string
	MeterID                       string
	MeterSubCategory              string
	MeterName                     string
	MeterRegion                   string
	Unit                          string
	ResourceLocation              string
	ConsumedService               string
	ResourceGroup                 string
	ResourceUri                   string
	ChargeType                    string
	UnitPrice                     string
	Quantity                      string
	UnitType                      string
	BillingPreTaxTotal            string
	BillingCurrency               string
	PricingPreTaxTotal            string
	PricingCurrency               string
	ServiceInfo1                  string
	ServiceInfo2                  string
	Tags                          string
	AdditionalInfo                string
	EffectiveUnitPrice            string
	PcToBcExchangeRate            string
	PcToBcExchangeRateDate        time.Time
	EntitlementID                 string
	EntitlementDescription        string
	PartnerEarnedCreditPercentage string
	CreditPercentage              string
	CreditType                    string
	BenefitOrderID                string
	BenefitID                     string
	BenefitType                   string
	UserID                        int32
}

type User struct {
	ID        int32
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
}
